#!/usr/bin/env python3
"""
Shadow-LWE analysis: compression, the rate-matching frontier, and aggregation depth.
Reads results/shadow_sweep.csv (FPGA P&R) plus the measured RTL cycle counts, and
writes paper/tables.tex and results/figures/*.
"""
import csv, os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

N, W = 630, 32
SEED_B, CT_B = (128 + W) // 8, (N + 1) * W // 8      # 20 B vs 2524 B

# measured RTL latency (tb_shadow.sv), cycles per encrypted record
CYC = {(1, 2): 4124, (1, 4): 4137, (1, 8): 4137, (1, 16): 4189,
       (2, 4): 2229, (2, 8): 2229, (3, 4): 1593, (3, 8): 1593,
       (4, 4): 1275, (4, 8): 1275, (6, 4): 957, (6, 8): 957,
       (12, 4): 639, (12, 8): 639}

rows = []
p = os.path.join(ROOT, "results", "shadow_sweep.csv")
if os.path.exists(p):
    for r in csv.DictReader(p and open(p)):
        rows.append(dict(rpc=int(r["rpc"]), lanes=int(r["lanes"]), lut=int(r["lut"]),
                         ff=int(r["ff"]), dsp=int(r["dsp"]), bram=int(r["bram"]),
                         fmax=float(r["fmax_mhz"]), power=float(r["power_w"])))

def cyc_of(rpc, lanes):
    if (rpc, lanes) in CYC: return CYC[(rpc, lanes)]
    same = [v for (r, l), v in CYC.items() if r == rpc]
    return same[0] if same else None

print(f"=== compression ===\n  {CT_B} B -> {SEED_B} B  = {CT_B/SEED_B:.1f}x\n")
print("=== rate-matching frontier (measured) ===")
print("  rpc lanes    LUT   Fmax    cyc/rec   us/rec   records/s")
for r in sorted(rows, key=lambda d: (d["rpc"], d["lanes"])):
    c = cyc_of(r["rpc"], r["lanes"])
    us = c / (r["fmax"] * 1e6) * 1e6
    print(f"  {r['rpc']:3d} {r['lanes']:5d} {r['lut']:6d} {r['fmax']:6.0f} "
          f"{c:8d} {us:8.1f} {1e6/us:11.0f}")

# the finding: lanes do not help
l_pairs = [(a, b) for a in rows for b in rows
           if a["rpc"] == b["rpc"] and a["lanes"] < b["lanes"]]
print("\n=== effect of adding MAC lanes at fixed generator rate ===")
for a, b in l_pairs:
    ca, cb = cyc_of(a["rpc"], a["lanes"]), cyc_of(b["rpc"], b["lanes"])
    print(f"  rpc={a['rpc']}: lanes {a['lanes']}->{b['lanes']} costs "
          f"{b['lut']-a['lut']:+d} LUT ({100*(b['lut']/a['lut']-1):+.0f}%) "
          f"and changes latency by {cb-ca:+d} cyc ({100*(cb/ca-1):+.1f}%)")

# ---------------------------------------------------------------- figures ----
try:
    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:
    print("\n(matplotlib unavailable; skipping figures)"); raise SystemExit

FIG = os.path.join(ROOT, "results", "figures"); os.makedirs(FIG, exist_ok=True)
C_BLUE, C_ORANGE, C_AQUA = "#2a78d6", "#eb6834", "#1baf7a"
INK, MUTED = "#0b0b0b", "#898781"
plt.rcParams.update({"font.size": 7.5, "axes.edgecolor": "#c3c2b7", "axes.linewidth": 0.6,
                     "xtick.color": MUTED, "ytick.color": MUTED, "text.color": INK,
                     "axes.labelcolor": "#52514e"})

l2 = sorted([r for r in rows if r["lanes"] == 2], key=lambda d: d["rpc"])
if l2:
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(7.0, 2.35))
    rpc = [r["rpc"] for r in l2]; lut = [r["lut"] for r in l2]
    fm = [r["fmax"] for r in l2]
    thr = [1e6 / (cyc_of(r["rpc"], 2) / (r["fmax"] * 1e6) * 1e6) for r in l2]

    a1.plot(rpc, lut, "-o", ms=4.5, color=C_ORANGE, label="LUT")
    a1.set_xlabel("Ascon rounds per cycle"); a1.set_ylabel("LUTs", color=C_ORANGE)
    a1.tick_params(axis="y", colors=C_ORANGE)
    a1b = a1.twinx()
    a1b.plot(rpc, fm, "-s", ms=4.5, color=C_BLUE, label="$F_{max}$")
    a1b.set_ylabel("$F_{max}$ (MHz)", color=C_BLUE); a1b.tick_params(axis="y", colors=C_BLUE)
    a1.set_title("Faster mask expansion costs area and clock", fontsize=8)
    for s in ("top",): a1.spines[s].set_visible(False); a1b.spines[s].set_visible(False)

    a2.plot(rpc, thr, "-o", ms=4.5, color=C_AQUA)
    a2.set_xlabel("Ascon rounds per cycle"); a2.set_ylabel("encrypted records/s")
    a2.set_title("Real-time gain saturates", fontsize=8)
    for s in ("top", "right"): a2.spines[s].set_visible(False)
    fig.tight_layout()
    for e in ("pdf", "png"):
        fig.savefig(os.path.join(FIG, f"fig_frontier.{e}"), bbox_inches="tight", dpi=400)
    print("\nwrote results/figures/fig_frontier.pdf")

# ---------------------------------------------------------------- tables -----
T = ["% AUTO-GENERATED by model/analyze.py"]
T.append(r"""\begin{table}[tb]\centering\setlength{\tabcolsep}{5pt}\footnotesize
\caption{Ciphertext size for one encrypted bit, $N=630$, $W=32$. Expanding the mask on
chip from a public seed removes it from the wire entirely.}
\label{tab:compress}
\begin{tabular}{lrr}
\toprule
transmitted & size & ratio\\\midrule
$(a[0\ldots N{-}1],\,b)$, standard & %d\,B & 1$\times$\\
$(\text{seed},\,b)$, this work & \textbf{%d\,B} & \textbf{%.0f$\times$}\\
\bottomrule\end{tabular}\end{table}""" % (CT_B, SEED_B, CT_B / SEED_B))

if rows:
    body = "".join(
        r"%d & %d & %d & %d & %.0f & %d & %.0f\\" % (
            r["rpc"], r["lanes"], r["lut"], r["ff"], r["fmax"],
            cyc_of(r["rpc"], r["lanes"]),
            1e6 / (cyc_of(r["rpc"], r["lanes"]) / (r["fmax"] * 1e6) * 1e6)) + "\n"
        for r in sorted(rows, key=lambda d: (d["rpc"], d["lanes"])))
    T.append(r"""\begin{table}[tb]\centering\setlength{\tabcolsep}{4pt}\footnotesize
\caption{Rate-matching frontier on xck26 (OOC place\&route, zero DSP and zero BRAM at
every point). Latency is measured on the RTL. Adding MAC lanes at a fixed generator rate
costs area without reducing latency.}
\label{tab:frontier}
\begin{tabular}{rrrrrrr}
\toprule
rnd/cyc & lanes & LUT & FF & $F_{\max}$ & cyc/rec & rec/s\\\midrule
%s\bottomrule\end{tabular}\end{table}""" % body)

open(os.path.join(ROOT, "paper", "tables.tex"), "w").write("\n".join(T) + "\n")
print("wrote paper/tables.tex")
